"""Added timestamp column

Revision ID: 03268681781e
Revises: 
Create Date: 2023-08-18 20:15:14.271605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03268681781e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
